/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppProgressRouteImport } from './routes/app.progress'
import { Route as AppTutorRouteImport } from './routes/app.tutor'
import { Route as AppLessonsLessonIdRouteImport } from './routes/app.lessons.$lessonId'
import { Route as AppSubjectsIndexRouteImport } from './routes/app.subjects.index'
import { Route as AppSubjectsSubjectIdRouteImport } from './routes/app.subjects.$subjectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/app/progress',
  path: '/app/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTutorRoute = AppTutorRouteImport.update({
  id: '/app/tutor',
  path: '/app/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLessonsLessonIdRoute = AppLessonsLessonIdRouteImport.update({
  id: '/app/lessons/$lessonId',
  path: '/app/lessons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubjectsIndexRoute = AppSubjectsIndexRouteImport.update({
  id: '/app/subjects/',
  path: '/app/subjects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubjectsSubjectIdRoute = AppSubjectsSubjectIdRouteImport.update({
  id: '/app/subjects/$subjectId',
  path: '/app/subjects/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/tutor': typeof AppTutorRoute
  '/app/lessons/$lessonId': typeof AppLessonsLessonIdRoute
  '/app/subjects/$subjectId': typeof AppSubjectsSubjectIdRoute
  '/app/subjects/': typeof AppSubjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/tutor': typeof AppTutorRoute
  '/app/lessons/$lessonId': typeof AppLessonsLessonIdRoute
  '/app/subjects/$subjectId': typeof AppSubjectsSubjectIdRoute
  '/app/subjects': typeof AppSubjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/tutor': typeof AppTutorRoute
  '/app/lessons/$lessonId': typeof AppLessonsLessonIdRoute
  '/app/subjects/$subjectId': typeof AppSubjectsSubjectIdRoute
  '/app/subjects/': typeof AppSubjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/app/dashboard'
    | '/app/profile'
    | '/app/progress'
    | '/app/tutor'
    | '/app/lessons/$lessonId'
    | '/app/subjects/$subjectId'
    | '/app/subjects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/app/dashboard'
    | '/app/profile'
    | '/app/progress'
    | '/app/tutor'
    | '/app/lessons/$lessonId'
    | '/app/subjects/$subjectId'
    | '/app/subjects'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/app/dashboard'
    | '/app/profile'
    | '/app/progress'
    | '/app/tutor'
    | '/app/lessons/$lessonId'
    | '/app/subjects/$subjectId'
    | '/app/subjects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppTutorRoute: typeof AppTutorRoute
  AppLessonsLessonIdRoute: typeof AppLessonsLessonIdRoute
  AppSubjectsSubjectIdRoute: typeof AppSubjectsSubjectIdRoute
  AppSubjectsIndexRoute: typeof AppSubjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/app/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tutor': {
      id: '/app/tutor'
      path: '/app/tutor'
      fullPath: '/app/tutor'
      preLoaderRoute: typeof AppTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/lessons/$lessonId': {
      id: '/app/lessons/$lessonId'
      path: '/app/lessons/$lessonId'
      fullPath: '/app/lessons/$lessonId'
      preLoaderRoute: typeof AppLessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/subjects/': {
      id: '/app/subjects/'
      path: '/app/subjects'
      fullPath: '/app/subjects/'
      preLoaderRoute: typeof AppSubjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/subjects/$subjectId': {
      id: '/app/subjects/$subjectId'
      path: '/app/subjects/$subjectId'
      fullPath: '/app/subjects/$subjectId'
      preLoaderRoute: typeof AppSubjectsSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppTutorRoute: AppTutorRoute,
  AppLessonsLessonIdRoute: AppLessonsLessonIdRoute,
  AppSubjectsSubjectIdRoute: AppSubjectsSubjectIdRoute,
  AppSubjectsIndexRoute: AppSubjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
