/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTutorRouteImport } from './routes/app.tutor'
import { Route as AppLessonsLessonIdRouteImport } from './routes/app.lessons.$lessonId'
import { Route as AppSubjectsSubjectIdRouteImport } from './routes/app.subjects.$subjectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTutorRoute = AppTutorRouteImport.update({
  id: '/app/tutor',
  path: '/app/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLessonsLessonIdRoute = AppLessonsLessonIdRouteImport.update({
  id: '/app/lessons/$lessonId',
  path: '/app/lessons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubjectsSubjectIdRoute = AppSubjectsSubjectIdRouteImport.update({
  id: '/app/subjects/$subjectId',
  path: '/app/subjects/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/tutor': typeof AppTutorRoute
  '/app/lessons/$lessonId': typeof AppLessonsLessonIdRoute
  '/app/subjects/$subjectId': typeof AppSubjectsSubjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/tutor': typeof AppTutorRoute
  '/app/lessons/$lessonId': typeof AppLessonsLessonIdRoute
  '/app/subjects/$subjectId': typeof AppSubjectsSubjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/tutor': typeof AppTutorRoute
  '/app/lessons/$lessonId': typeof AppLessonsLessonIdRoute
  '/app/subjects/$subjectId': typeof AppSubjectsSubjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/app/tutor' | '/app/lessons/$lessonId' | '/app/subjects/$subjectId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app/tutor' | '/app/lessons/$lessonId' | '/app/subjects/$subjectId'
  id:
    | '__root__'
    | '/'
    | '/app/tutor'
    | '/app/lessons/$lessonId'
    | '/app/subjects/$subjectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppTutorRoute: typeof AppTutorRoute
  AppLessonsLessonIdRoute: typeof AppLessonsLessonIdRoute
  AppSubjectsSubjectIdRoute: typeof AppSubjectsSubjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tutor': {
      id: '/app/tutor'
      path: '/app/tutor'
      fullPath: '/app/tutor'
      preLoaderRoute: typeof AppTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/lessons/$lessonId': {
      id: '/app/lessons/$lessonId'
      path: '/app/lessons/$lessonId'
      fullPath: '/app/lessons/$lessonId'
      preLoaderRoute: typeof AppLessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/subjects/$subjectId': {
      id: '/app/subjects/$subjectId'
      path: '/app/subjects/$subjectId'
      fullPath: '/app/subjects/$subjectId'
      preLoaderRoute: typeof AppSubjectsSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppTutorRoute: AppTutorRoute,
  AppLessonsLessonIdRoute: AppLessonsLessonIdRoute,
  AppSubjectsSubjectIdRoute: AppSubjectsSubjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
